[versions]
androidGradlePlugin = "7.3.1"
androidxAppCompat = "1.5.1"
androidxCore = "1.9.0"
androidMaterial = "1.7.0"
kotlin = "1.7.20"
jacoco = "0.8.8"
junit = "4.4"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jacoco = { id = "jacoco", version.ref = "jacoco" }
