[versions]
androidGradlePlugin = "7.3.1"
androidxAppCompat = "1.5.1"
androidxCore = "1.9.0"
androidxBenchmark = "1.1.1"
androidxJunit = "1.1.4"
androidMaterial = "1.7.0"
kotlin = "1.7.20"
jacoco = "0.8.8"
jacocoPlugin = "0.16.0"
junit = "4.4"
detekt = "1.22.0"
ktlint = "0.43.2"
ktlintPlugin = "11.0.0"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-benchmark = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidxBenchmark" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxJunit" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
benchmark = { id = "androidx.benchmark", version.ref = "androidxBenchmark" }
jacoco = { id = "com.vanniktech.android.junit.jacoco", version.ref = "jacocoPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
