name: Microbenchmark Firebase Test Lab
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - setup/microbenchmark

jobs:
  build:
    name: Microbenchmark to Firebase Test Lab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/gradle-build-action@v2.1.4
      - run: |
          ./gradlew :benchmark:packageReleaseAndroidTest :app:assembleRelease

      - name: microbenchmarks
        uses: martinbonnin/run-benchmarks@main
        with:
          google_services_json: ${{ secrets.FIREBASE_JSON }}

          app_apk: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          test_apk: 'benchmark/build/intermediates/apk/androidTest/release/benchmark-release-androidTest.apk'
          device_model: 'redfin,locale=en,orientation=portrait'